language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MetadataTools"); Pkg.test("MetadataTools"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("MetadataTools")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'